// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Feature struct {
	ImageEncoded                  []byte   `protobuf:"bytes,1,opt,name=image_encoded,json=imageEncoded,proto3" json:"image_encoded,omitempty"`
	ImageFilename                 string   `protobuf:"bytes,2,opt,name=image_filename,json=imageFilename,proto3" json:"image_filename,omitempty"`
	ImageFormat                   string   `protobuf:"bytes,3,opt,name=image_format,json=imageFormat,proto3" json:"image_format,omitempty"`
	ImageHeight                   int32    `protobuf:"varint,4,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"`
	ImageWidth                    int32    `protobuf:"varint,5,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`
	ImageSegmentationClassEncoded []byte   `protobuf:"bytes,6,opt,name=image_segmentation_class_encoded,json=imageSegmentationClassEncoded,proto3" json:"image_segmentation_class_encoded,omitempty"`
	ImageSegmentationClassFormat  string   `protobuf:"bytes,7,opt,name=image_segmentation_class_format,json=imageSegmentationClassFormat,proto3" json:"image_segmentation_class_format,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetImageEncoded() []byte {
	if m != nil {
		return m.ImageEncoded
	}
	return nil
}

func (m *Feature) GetImageFilename() string {
	if m != nil {
		return m.ImageFilename
	}
	return ""
}

func (m *Feature) GetImageFormat() string {
	if m != nil {
		return m.ImageFormat
	}
	return ""
}

func (m *Feature) GetImageHeight() int32 {
	if m != nil {
		return m.ImageHeight
	}
	return 0
}

func (m *Feature) GetImageWidth() int32 {
	if m != nil {
		return m.ImageWidth
	}
	return 0
}

func (m *Feature) GetImageSegmentationClassEncoded() []byte {
	if m != nil {
		return m.ImageSegmentationClassEncoded
	}
	return nil
}

func (m *Feature) GetImageSegmentationClassFormat() string {
	if m != nil {
		return m.ImageSegmentationClassFormat
	}
	return ""
}

type Features struct {
	Features             []*Feature `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Features) Reset()         { *m = Features{} }
func (m *Features) String() string { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()    {}
func (*Features) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *Features) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features.Unmarshal(m, b)
}
func (m *Features) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features.Marshal(b, m, deterministic)
}
func (m *Features) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features.Merge(m, src)
}
func (m *Features) XXX_Size() int {
	return xxx_messageInfo_Features.Size(m)
}
func (m *Features) XXX_DiscardUnknown() {
	xxx_messageInfo_Features.DiscardUnknown(m)
}

var xxx_messageInfo_Features proto.InternalMessageInfo

func (m *Features) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type Response struct {
	ImageFilename                string   `protobuf:"bytes,1,opt,name=image_filename,json=imageFilename,proto3" json:"image_filename,omitempty"`
	ImageRecognitionNumbers      string   `protobuf:"bytes,2,opt,name=image_recognition_numbers,json=imageRecognitionNumbers,proto3" json:"image_recognition_numbers,omitempty"`
	ImageRecognitionVerification string   `protobuf:"bytes,3,opt,name=image_recognition_verification,json=imageRecognitionVerification,proto3" json:"image_recognition_verification,omitempty"`
	ImageRecognitionDates        string   `protobuf:"bytes,4,opt,name=image_recognition_dates,json=imageRecognitionDates,proto3" json:"image_recognition_dates,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetImageFilename() string {
	if m != nil {
		return m.ImageFilename
	}
	return ""
}

func (m *Response) GetImageRecognitionNumbers() string {
	if m != nil {
		return m.ImageRecognitionNumbers
	}
	return ""
}

func (m *Response) GetImageRecognitionVerification() string {
	if m != nil {
		return m.ImageRecognitionVerification
	}
	return ""
}

func (m *Response) GetImageRecognitionDates() string {
	if m != nil {
		return m.ImageRecognitionDates
	}
	return ""
}

type Responses struct {
	Responses            []*Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Responses) Reset()         { *m = Responses{} }
func (m *Responses) String() string { return proto.CompactTextString(m) }
func (*Responses) ProtoMessage()    {}
func (*Responses) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{3}
}

func (m *Responses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Responses.Unmarshal(m, b)
}
func (m *Responses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Responses.Marshal(b, m, deterministic)
}
func (m *Responses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Responses.Merge(m, src)
}
func (m *Responses) XXX_Size() int {
	return xxx_messageInfo_Responses.Size(m)
}
func (m *Responses) XXX_DiscardUnknown() {
	xxx_messageInfo_Responses.DiscardUnknown(m)
}

var xxx_messageInfo_Responses proto.InternalMessageInfo

func (m *Responses) GetResponses() []*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

func init() {
	proto.RegisterType((*Feature)(nil), "protocol.Feature")
	proto.RegisterType((*Features)(nil), "protocol.Features")
	proto.RegisterType((*Response)(nil), "protocol.Response")
	proto.RegisterType((*Responses)(nil), "protocol.Responses")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x6a, 0x13, 0x41,
	0x14, 0xc6, 0x99, 0xd4, 0x36, 0xc9, 0x49, 0xaa, 0x38, 0x2a, 0x5d, 0x43, 0x6a, 0xd7, 0x2d, 0x42,
	0x10, 0x4c, 0xb4, 0x82, 0x60, 0xc1, 0x2b, 0xfb, 0xc7, 0x2b, 0x91, 0x15, 0xf4, 0x46, 0x08, 0xd3,
	0xcd, 0xc9, 0x66, 0x60, 0x77, 0x26, 0xec, 0x4c, 0x52, 0xbc, 0xf5, 0x15, 0x7c, 0x1a, 0xdf, 0xc1,
	0x3b, 0x5f, 0xc1, 0x3b, 0x5f, 0x42, 0x72, 0x66, 0xb6, 0x09, 0xd9, 0xed, 0xd5, 0xee, 0x7c, 0xe7,
	0x77, 0x3e, 0xe6, 0x3b, 0x67, 0x60, 0x3f, 0x15, 0x16, 0xaf, 0xc5, 0xf7, 0xe1, 0xbc, 0xd0, 0x56,
	0xf3, 0x16, 0x7d, 0x12, 0x9d, 0xf5, 0xfa, 0xa9, 0xd6, 0x69, 0x86, 0x23, 0x31, 0x97, 0x23, 0xa1,
	0x94, 0xb6, 0xc2, 0x4a, 0xad, 0x8c, 0xe3, 0xa2, 0xdf, 0x0d, 0x68, 0x5e, 0xa0, 0xb0, 0x8b, 0x02,
	0xf9, 0x31, 0xec, 0xcb, 0x5c, 0xa4, 0x38, 0x46, 0x95, 0xe8, 0x09, 0x4e, 0x02, 0x16, 0xb2, 0x41,
	0x37, 0xee, 0x92, 0x78, 0xee, 0x34, 0xfe, 0x0c, 0xee, 0x3a, 0x68, 0x2a, 0x33, 0x54, 0x22, 0xc7,
	0xa0, 0x11, 0xb2, 0x41, 0x3b, 0x76, 0xad, 0x17, 0x5e, 0xe4, 0x4f, 0xa1, 0xeb, 0x31, 0x5d, 0xe4,
	0xc2, 0x06, 0x3b, 0x04, 0x75, 0x1c, 0x44, 0xd2, 0x1a, 0x99, 0xa1, 0x4c, 0x67, 0x36, 0xb8, 0x13,
	0xb2, 0xc1, 0xae, 0x47, 0x3e, 0x90, 0xc4, 0x8f, 0xc0, 0x1d, 0xc7, 0xd7, 0x72, 0x62, 0x67, 0xc1,
	0x2e, 0x11, 0x40, 0xd2, 0xd7, 0x95, 0xc2, 0x2f, 0x21, 0x74, 0x80, 0xc1, 0x34, 0x47, 0xe5, 0xb2,
	0x8d, 0x93, 0x4c, 0x18, 0x73, 0x93, 0x62, 0x8f, 0x52, 0x1c, 0x12, 0xf7, 0x79, 0x03, 0x7b, 0xbf,
	0xa2, 0xca, 0x58, 0xe7, 0x70, 0x74, 0xab, 0x91, 0x8f, 0xd0, 0xa4, 0x08, 0xfd, 0x7a, 0x1f, 0x97,
	0x29, 0x7a, 0x0b, 0x2d, 0x3f, 0x4d, 0xc3, 0x5f, 0x40, 0x6b, 0xea, 0xff, 0x03, 0x16, 0xee, 0x0c,
	0x3a, 0x27, 0xf7, 0x87, 0xe5, 0x56, 0x86, 0x9e, 0x8a, 0x6f, 0x90, 0xe8, 0x1f, 0x83, 0x56, 0x8c,
	0x66, 0xae, 0x95, 0xc1, 0x9a, 0x29, 0xb3, 0xba, 0x29, 0x9f, 0xc2, 0x63, 0x87, 0x15, 0x98, 0xe8,
	0x54, 0x49, 0xba, 0xb4, 0x5a, 0xe4, 0x57, 0x58, 0x18, 0xbf, 0x97, 0x03, 0x02, 0xe2, 0x75, 0xfd,
	0xa3, 0x2b, 0xf3, 0x33, 0x78, 0x52, 0xed, 0x5d, 0x62, 0x21, 0xa7, 0x32, 0xa1, 0x5c, 0x7e, 0x67,
	0xfd, 0x6d, 0x83, 0x2f, 0x1b, 0x0c, 0x7f, 0x03, 0x07, 0x55, 0x97, 0x89, 0xb0, 0x68, 0x68, 0x9f,
	0xed, 0xf8, 0xd1, 0x76, 0xfb, 0xd9, 0xaa, 0x18, 0xbd, 0x83, 0x76, 0x19, 0xd6, 0xf0, 0x97, 0xd0,
	0x2e, 0xca, 0x83, 0x1f, 0x15, 0x5f, 0x8f, 0xaa, 0xe4, 0xe2, 0x35, 0x74, 0xf2, 0x8b, 0x41, 0xf3,
	0xd2, 0x3d, 0x78, 0xfe, 0x09, 0x3a, 0x05, 0x26, 0xcb, 0xf2, 0x15, 0x57, 0x87, 0xdc, 0xab, 0x31,
	0x8b, 0x7a, 0x3f, 0xfe, 0xfc, 0xfd, 0xd9, 0x78, 0x18, 0xdd, 0x1b, 0x2d, 0x5f, 0x8d, 0x36, 0x2e,
	0x7f, 0xca, 0x9e, 0xf3, 0x6f, 0xd0, 0xdd, 0x70, 0x34, 0x9c, 0x57, 0x2c, 0x4d, 0xef, 0x41, 0xd5,
	0xd3, 0x44, 0xc7, 0x64, 0x7a, 0x18, 0x05, 0x2b, 0xd3, 0x7c, 0x91, 0x59, 0x39, 0xcf, 0x70, 0xcb,
	0xfd, 0x6a, 0x8f, 0x1a, 0x5f, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x54, 0xf7, 0x56, 0xb2,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	RecvFeature(ctx context.Context, in *Feature, opts ...grpc.CallOption) (*Response, error)
	RecvFeatures(ctx context.Context, in *Features, opts ...grpc.CallOption) (*Responses, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) RecvFeature(ctx context.Context, in *Feature, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protocol.Gateway/recvFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) RecvFeatures(ctx context.Context, in *Features, opts ...grpc.CallOption) (*Responses, error) {
	out := new(Responses)
	err := c.cc.Invoke(ctx, "/protocol.Gateway/recvFeatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	RecvFeature(context.Context, *Feature) (*Response, error)
	RecvFeatures(context.Context, *Features) (*Responses, error)
}

// UnimplementedGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (*UnimplementedGatewayServer) RecvFeature(ctx context.Context, req *Feature) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecvFeature not implemented")
}
func (*UnimplementedGatewayServer) RecvFeatures(ctx context.Context, req *Features) (*Responses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecvFeatures not implemented")
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_RecvFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Feature)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).RecvFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Gateway/RecvFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).RecvFeature(ctx, req.(*Feature))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_RecvFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Features)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).RecvFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Gateway/RecvFeatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).RecvFeatures(ctx, req.(*Features))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "recvFeature",
			Handler:    _Gateway_RecvFeature_Handler,
		},
		{
			MethodName: "recvFeatures",
			Handler:    _Gateway_RecvFeatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
